"""
Django settings for vegitable project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import json
import os
import mimetypes
from decouple import config

mimetypes.add_type("text/css", ".css", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _split_csv(value):
    return [item.strip() for item in value.split(',') if item.strip()]


def _resolve_optional_path(value):
    if not value:
        return None
    candidate = Path(value)
    if candidate.is_absolute():
        return str(candidate)
    return str(BASE_DIR / candidate)


def _load_optional_json_object(value, setting_name):
    if not value:
        return {}
    parsed_value = json.loads(value)
    if not isinstance(parsed_value, dict):
        raise ValueError(f'{setting_name} must be a JSON object.')
    return parsed_value


def _load_optional_json_file(path_value):
    if not path_value:
        return {}
    candidate = Path(path_value)
    if not candidate.exists():
        return {}
    with candidate.open('r', encoding='utf-8') as file_handle:
        parsed_value = json.load(file_handle)
    if not isinstance(parsed_value, dict):
        return {}
    return parsed_value

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-dev-only-change-me',
)

# Determine environment
DEBUG = config('DEBUG', cast=bool, default=False)
FIREBASE_ENABLED = config('FIREBASE_ENABLED', cast=bool, default=False)
FIREBASE_AUTO_INIT = config('FIREBASE_AUTO_INIT', cast=bool, default=False)
USE_FIREBASE_MOBILE_SALES = config('USE_FIREBASE_MOBILE_SALES', cast=bool, default=False)
USE_FIREBASE_CUSTOMER_LEDGER = config('USE_FIREBASE_CUSTOMER_LEDGER', cast=bool, default=False)
USE_FIREBASE_FARMER_LEDGER = config('USE_FIREBASE_FARMER_LEDGER', cast=bool, default=False)
USE_FIREBASE_ARRIVAL = config('USE_FIREBASE_ARRIVAL', cast=bool, default=False)
USE_FIREBASE_SALES = config('USE_FIREBASE_SALES', cast=bool, default=False)
USE_FIREBASE_CREDIT = config('USE_FIREBASE_CREDIT', cast=bool, default=False)
USE_FIREBASE_PATTI = config('USE_FIREBASE_PATTI', cast=bool, default=False)
USE_FIREBASE_EXPENDITURE = config('USE_FIREBASE_EXPENDITURE', cast=bool, default=False)
FIREBASE_CREDENTIAL_PATH = _resolve_optional_path(
    config('FIREBASE_CREDENTIAL_PATH', default='')
)
FIREBASE_WEB_CONFIG_PATH = _resolve_optional_path(
    config('FIREBASE_WEB_CONFIG_PATH', default='../firebase.json')
)
FIREBASE_WEB_CONFIG = _load_optional_json_file(FIREBASE_WEB_CONFIG_PATH)
FIREBASE_PROJECT_ID = config(
    'FIREBASE_PROJECT_ID',
    default=FIREBASE_WEB_CONFIG.get('projectId', ''),
).strip()
FIREBASE_OPTIONS = _load_optional_json_object(
    config('FIREBASE_OPTIONS_JSON', default='').strip(),
    'FIREBASE_OPTIONS_JSON',
)
if FIREBASE_PROJECT_ID:
    FIREBASE_OPTIONS.setdefault('projectId', FIREBASE_PROJECT_ID)
if not FIREBASE_OPTIONS:
    FIREBASE_OPTIONS = None

# Allow all hosts in development, restrict in production
DEFAULT_ALLOWED_HOSTS = 'mbillingtool.pythonanywhere.com,localhost,127.0.0.1'
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=DEFAULT_ALLOWED_HOSTS, cast=_split_csv)
if DEBUG:
    ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'corsheaders',
    'shops'
]

if FIREBASE_ENABLED or FIREBASE_AUTO_INIT:
    INSTALLED_APPS.append('django_firebase_orm.apps.DjangoFirebaseOrmConfig')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication'
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'vegitable.urls'
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='',
    cast=_split_csv,
)
SESSION_COOKIE_AGE = 3600
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# HTTPS enforcement (only in production)
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vegitable.wsgi.application'

# Database settings
if config('USE_CLOUD_DB', cast=bool, default=False):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('CLOUD_DB_NAME', default='mbillingtool$vegitableshop'),
            'USER': config('CLOUD_DB_USER', default='mbillingtool'),
            'PASSWORD': config('CLOUD_DB_PASSWORD', default=''),
            'HOST': config('CLOUD_DB_HOST', default='mbillingtool.mysql.pythonanywhere-services.com'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': config('LOCAL_DB_ENGINE', default='django.db.backends.sqlite3'),
            'NAME': config('LOCAL_DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
            'USER': config('LOCAL_DB_USER', default=''),
            'PASSWORD': config('LOCAL_DB_PASSWORD', default=''),
            'HOST': config('LOCAL_DB_HOST', default=''),
            'PORT': config('LOCAL_DB_PORT', default=''),
        }
    }

if DATABASES['default']['ENGINE'].endswith('mysql'):
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].setdefault('init_command', "SET sql_mode='STRICT_TRANS_TABLES'")

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static and Media files
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "assets")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH = False
