description: >
  Install Google's Chrome browser, for use in browser testing. Note:
  only the latest stable release can be installed, as Google does not
  maintain a public archive of previous releases. Supports Debian/Ubuntu
  Linux, Alpine Linux (via Chromium), and macOS environments.

parameters:
  replace-existing:
    type: boolean
    default: false
    description: >
      If there is an existing installation of Google Chrome, replace it
      with the latest stable release?
  chrome-version:
    default: latest
    type: string
    description: >
      Version of Chrome to install, defaults to the latest stable release.
      To install an older release, specify a full chrome version number,
      e.g., 85.0.4183.83
      Only supported on centos and debian
      If replace-existing is false, this version is ignored.
  channel:
    description: |
      The release channel of Google Chrome to use. Defaults to 'stable'.
    type: enum
    enum: [ "stable", "beta" ]
    default: "stable"

steps:
  - run:
      name: Install Google Chrome
      environment:
        ORB_PARAM_CHROME_VERSION: <<parameters.chrome-version>>
        ORB_PARAM_REPLACE_EXISTING: <<parameters.replace-existing>>
        ORB_PARAM_CHANNEL: << parameters.channel >>
      command: <<include(scripts/install-chrome.sh)>>