name: Build Cloud and Reload Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_reload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Build Script
        run: python script/build_cloud.py

  reload_webapp:
    runs-on: ubuntu-latest
    needs: build_and_reload
    if: ${{ needs.build_and_reload.result == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Reload Web App
        run: python script/reload_webapp.py
