# Generated by Django 5.1.5 on 2025-01-21 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_no', models.CharField(max_length=100)),
                ('lorry_no', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('patti_name', models.CharField(max_length=50)),
                ('total_bags', models.IntegerField()),
                ('Empty_data', models.BooleanField(default=True)),
                ('arrival_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreditBillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('initial_credit_bill_amount', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PattiEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lorry_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('advance', models.FloatField(max_length=100)),
                ('farmer_name', models.CharField(max_length=100)),
                ('total_weight', models.FloatField(max_length=100)),
                ('hamali', models.FloatField(max_length=100)),
                ('net_amount', models.FloatField(max_length=100)),
                ('patti_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesBillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('rmc', models.FloatField(max_length=50)),
                ('commission', models.FloatField(max_length=50)),
                ('cooli', models.FloatField(max_length=50)),
                ('total_amount', models.FloatField(max_length=50)),
                ('paid_amount', models.FloatField(max_length=50)),
                ('balance_amount', models.FloatField(max_length=50)),
                ('Empty_data', models.BooleanField(default=True)),
                ('sales_bill_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('former_name', models.CharField(max_length=50)),
                ('initial_qty', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('weight', models.FloatField(max_length=100)),
                ('remarks', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('advance', models.FloatField(default=0, max_length=100)),
                ('patti_status', models.BooleanField(default=False)),
                ('arrival_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.arrivalentry')),
            ],
        ),
        migrations.CreateModel(
            name='CreditBillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('credit_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.creditbillentry')),
            ],
        ),
        migrations.CreateModel(
            name='PattiEntryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('lot_no', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('amount', models.FloatField(max_length=100)),
                ('patti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.pattientry')),
            ],
        ),
        migrations.AddField(
            model_name='creditbillentry',
            name='sales_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.salesbillentry'),
        ),
        migrations.CreateModel(
            name='SalesBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=10)),
                ('bags', models.CharField(max_length=50)),
                ('net_weight', models.FloatField(max_length=50)),
                ('rates', models.FloatField(max_length=50)),
                ('amount', models.FloatField(max_length=50)),
                ('Sales_Bill_Entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.salesbillentry')),
                ('arrival_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.arrivalgoods')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_location', models.CharField(max_length=255)),
                ('shop_address', models.CharField(max_length=255)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salesbillentry',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='pattientry',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.CreateModel(
            name='MobileSalesBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lot_no', models.CharField(max_length=100)),
                ('total_bags', models.IntegerField()),
                ('net_weight', models.FloatField(max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_entry_prefix', models.CharField(max_length=50)),
                ('expenditure_entry_counter', models.IntegerField()),
                ('arrival_entry_prefix', models.CharField(max_length=50)),
                ('arrival_entry_counter', models.IntegerField()),
                ('sales_bill_entry_prefix', models.CharField(max_length=50)),
                ('sales_bill_entry_counter', models.IntegerField()),
                ('patti_entry_prefix', models.CharField(max_length=50)),
                ('patti_entry_counter', models.IntegerField()),
                ('customer_ledger_prefix', models.CharField(max_length=50)),
                ('customer_ledger_counter', models.IntegerField()),
                ('farmer_ledger_prefix', models.CharField(max_length=50)),
                ('farmer_ledger_counter', models.IntegerField()),
                ('credit_bill_entry_prefix', models.CharField(max_length=50)),
                ('credit_bill_entry_counter', models.IntegerField()),
                ('shilk_entry_prefix', models.CharField(max_length=50)),
                ('shilk_entry_counter', models.IntegerField()),
                ('inventory_prefix', models.CharField(max_length=50)),
                ('inventory_counter', models.IntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=400)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expense_type', models.CharField(max_length=50)),
                ('amount', models.FloatField(max_length=100)),
                ('remark', models.CharField(max_length=255)),
                ('Empty_data', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
        migrations.AddField(
            model_name='creditbillentry',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='arrivalgoods',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='arrivalentry',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
    ]
