# Generated by Django 4.0.5 on 2022-07-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival_goods',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
