# Generated by Django 4.2.1 on 2023-06-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('sales_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.sales_bill_entry')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='CreditBillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(max_length=100)),
                ('credit_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.creditbillentry')),
            ],
        ),
    ]
