# Generated by Django 4.0.4 on 2022-05-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('former_name', models.CharField(max_length=50)),
                ('qty', models.FloatField(max_length=100)),
                ('weight', models.FloatField(max_length=100)),
                ('remarks', models.CharField(max_length=50)),
                ('arrival_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.arrival_entry')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
