# Generated by Django 4.1 on 2022-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_arrival_goods_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival_goods',
            name='patti_status',
            field=models.BooleanField(default=False),
        ),
    ]
