# Generated by Django 4.2.1 on 2023-07-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_creditbillentry_creditbillhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbillhistory',
            name='payment_mode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
