# Generated by Django 4.0.5 on 2022-07-14 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_misc_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival_goods',
            name='iteam_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
