# Generated by Django 4.2.1 on 2023-06-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_farmerledger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Misc_Entry',
            new_name='Expenditure_Entry',
        ),
    ]
