# Generated by Django 5.1 on 2024-08-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_creditbillhistory_payment_mode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arrival_Entry',
            new_name='ArrivalEntry',
        ),
        migrations.RenameModel(
            old_name='Arrival_Goods',
            new_name='ArrivalGoods',
        ),
        migrations.RenameModel(
            old_name='Expenditure_Entry',
            new_name='ExpenditureEntry',
        ),
        migrations.RenameModel(
            old_name='Patti_entry',
            new_name='PattiEntry',
        ),
        migrations.RenameModel(
            old_name='Patti_entry_list',
            new_name='PattiEntryList',
        ),
        migrations.RenameModel(
            old_name='Sales_Bill_Entry',
            new_name='SalesBillEntry',
        ),
        migrations.RenameModel(
            old_name='Sales_Bill_Iteam',
            new_name='SalesBillItem',
        ),
        migrations.RenameField(
            model_name='arrivalgoods',
            old_name='iteam_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='pattientrylist',
            old_name='iteam',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='salesbillitem',
            old_name='iteam_name',
            new_name='item_name',
        ),
    ]
