# Generated by Django 4.1 on 2022-10-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_arrival_goods_patti_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival_entry',
            name='Empty_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='misc_entry',
            name='Empty_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patti_entry',
            name='Empty_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sales_bill_entry',
            name='Empty_data',
            field=models.BooleanField(default=True),
        ),
    ]
