# Generated by Django 4.0.6 on 2022-07-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_sales_bill_iteam_sales_bill_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_bill_iteam',
            name='Sales_Bill_Entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shops.sales_bill_entry'),
            preserve_default=False,
        ),
    ]
