# Generated by Django 5.1.1 on 2024-09-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_creditbillentry_initial_credit_bill_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_entry_prefix', models.CharField(max_length=50)),
                ('expenditure_entry_counter', models.IntegerField()),
                ('arrival_entry_prefix', models.CharField(max_length=50)),
                ('arrival_entry_counter', models.IntegerField()),
                ('sales_bill_entry_prefix', models.CharField(max_length=50)),
                ('sales_bill_entry_counter', models.IntegerField()),
                ('patti_entry_prefix', models.CharField(max_length=50)),
                ('patti_entry_counter', models.IntegerField()),
                ('customer_ledger_prefix', models.CharField(max_length=50)),
                ('customer_ledger_counter', models.IntegerField()),
                ('farmer_ledger_prefix', models.CharField(max_length=50)),
                ('farmer_ledger_counter', models.IntegerField()),
                ('credit_bill_entry_prefix', models.CharField(max_length=50)),
                ('credit_bill_entry_counter', models.IntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
