# Generated by Django 5.1.1 on 2024-09-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalentry',
            name='arrival_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
