# Generated by Django 5.1.1 on 2024-10-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_arrivalentry_arrival_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbillentry',
            name='sales_bill_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
