# Generated by Django 5.1.1 on 2024-11-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_salesbillentry_sales_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='inventory_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='inventory_prefix',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='shilk_entry_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='shilk_entry_prefix',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
