# Generated by Django 5.1.1 on 2025-01-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_index_inventory_counter_index_inventory_prefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSalesBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lot_no', models.CharField(max_length=100)),
                ('total_bags', models.IntegerField()),
                ('net_weight', models.FloatField(max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
