# Generated by Django 5.1.1 on 2025-01-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_mobilesalesbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattientry',
            name='Empty_data',
        ),
    ]
